# Generated by Otto, do not edit manually.
# We dont really need infrastrucutre apart from the droplet itself
# so just caching variables.

variable "do_token" {}
variable "do_ssh_public_key_path" {}

variable "do_region" {
    description = "Region where we will operate."
}

# Configure the DigitalOcean Provider
provider "digitalocean" {
    token = "${var.do_token}"
}
