# Generated by Otto, do not edit manually.

variable "do_token" {
    description = "Token for DigitalOcean"
}

variable "region" {
    description = "Region where we will operate."
}

variable "ssh_public_key" {
    description = "Contents of an SSH public key to grant access to created instances"
}

provider "digitalocean" {
    token = "${var.do_token}"
}

# Create a droplet
resource "digitalocean_droplet" "otto" {
  image = "ubuntu-14-04-x64"
  name = "otto-1"
  region = "sfo1"
  size = "512mb"
}

# SSH key that app implementations can use to grant SSH access to instances
resource "digitalocean_ssh_key" "default" {
    name = "Otto"
    public_key = "${var.ssh_public_key}"
}
