# Generated by Otto, do not edit!
#
# This is the Vagrantfile generated by Otto for the development of
# this application/service. It should not be hand-edited. To modify the
# Vagrantfile, use the Appfile.

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"

  # Setup a synced folder from our working directory to /vagrant
  config.vm.synced_folder "{{ path.working }}", "/vagrant"

  # Enable SSH agent forwarding so getting private dependencies works
  config.ssh.forward_agent = true

  # Load all our fragments here for any dependencies.
  {% for fragment in dev_fragments %}
  {{ fragment|read }}
  {% endfor %}

  # Install Go build environment
  config.vm.provision "shell", inline: $script_golang

  # Make it so that `vagrant ssh` goes directly to the correct dir
  config.vm.provision "shell", inline:
    %Q[echo "cd /vagrant" >> /home/vagrant/.bashrc]
end

$script_golang = <<SCRIPT
set -e

echo "Downloading Go {{ dev_go_version }}..."
wget -q -O /home/vagrant/go.tar.gz https://storage.googleapis.com/golang/go{{ dev_go_version }}.linux-amd64.tar.gz

echo "Untarring Go..."
sudo tar -C /usr/local -xzf /home/vagrant/go.tar.gz

echo "Making GOPATH..."
sudo mkdir -p /opt/gopath
sudo chown vagrant:vagrant /opt/gopath

echo "Setting up PATH..."
echo 'export PATH=/opt/gopath/bin:/usr/local/go/bin:$PATH' >> /home/vagrant/.bashrc
echo 'export GOPATH=/opt/gopath' >> /home/vagrant/.bashrc

echo "Installing VCSs for go get..."
sudo apt-get update -y >/dev/null 2>&1
sudo apt-get install -y git bzr mercurial
SCRIPT
