# Generated by dependency for development: {{ name }}

${{ name }}_setup = <<COPY
# Copy our binary
sudo mv /tmp/dep-{{ name }} /usr/local/bin/{{ name }}

# Copy the upstart file
sudo mv /tmp/dep-{{ name }}.upstart.conf /etc/init/{{ name }}.conf

# Start it!
sudo start {{ name }}
COPY
# Copy files into a temp directory. The script will move them.
config.vm.provision "file",
  source: "{{ path.cache }}/dev-dep-output",
  destination: "/tmp/dep-{{ name }}"

config.vm.provision "file",
  source: "{{ path.compiled }}/dev-dep/build/upstart.conf",
  destination: "/tmp/dep-{{ name }}.upstart.conf"

config.vm.provision "shell",
  inline: ${{ name }}_setup
