// Code generated by go-bindata.
// sources:
// data/aws-vpc-public-private/deploy/main.tf
// data/aws-vpc-public-private/deploy/module/main.tf
// data/aws-vpc-public-private/deploy/module/outputs.tf
// data/aws-vpc-public-private/deploy/module/variables.tf
// data/aws-vpc-public-private/deploy/variables.tf
// DO NOT EDIT!

package consul

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"strings"
	"os"
	"time"
	"io/ioutil"
	"path/filepath"
)

func bindataRead(data, name string) ([]byte, error) {
	gz, err := gzip.NewReader(strings.NewReader(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name string
	size int64
	mode os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _dataAwsVpcPublicPrivateDeployMainTf = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xcc\x8f\xd1\x6e\x83\x20\x14\x86\xef\x79\x0a\x42\x76\x0b\x53\xcc\xdc\x6e\xf6\x2c\x0b\xca\xc9\x46\xa6\x40\x40\x68\x1b\xe3\xbb\x17\xa5\xa6\x6d\xd2\x18\x2f\xe5\x86\x9c\xef\xff\x4f\xe0\xb3\xce\x44\x25\xc1\x61\x22\x4e\x9e\xe0\x11\xe1\x74\x1c\xfc\x2a\xa3\xf1\x37\x26\x6f\x63\x14\x8e\xa5\xe8\x27\xb3\x89\xa0\x09\xa1\xde\xc8\xd0\x01\x26\xad\xd1\x3e\x74\xb4\x5c\xf7\xbc\x09\xae\x85\x79\x8f\xbd\xe7\x0e\x41\x4b\xa0\xb4\x84\xf3\xcc\x4b\xb2\xcc\xd6\xa9\x28\x06\xa0\xca\x2e\xb0\x60\x05\x2b\xd9\x57\xce\x44\xaf\x66\x98\x2e\x2a\x81\x7f\x54\x4d\x53\xe7\xe0\x1f\x2e\x54\x8b\x1e\xee\xff\xf2\xfe\x8f\x26\x3a\xe5\xdc\x87\x46\xc3\x40\x95\x7c\x28\x64\xb4\x3e\xc7\x6f\xcd\x68\xdb\xa7\x5a\x9e\x5f\xba\xf1\xfd\x6e\x7c\xc3\xed\xf3\x88\x6e\xd5\x7e\xb7\x6a\xc3\xad\x3e\x82\xdb\x35\x00\x00\xff\xff\x7b\xf3\xa7\x9e\xc8\x02\x00\x00"

func dataAwsVpcPublicPrivateDeployMainTfBytes() ([]byte, error) {
	return bindataRead(
		_dataAwsVpcPublicPrivateDeployMainTf,
		"data/aws-vpc-public-private/deploy/main.tf",
	)
}

func dataAwsVpcPublicPrivateDeployMainTf() (*asset, error) {
	bytes, err := dataAwsVpcPublicPrivateDeployMainTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/aws-vpc-public-private/deploy/main.tf", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _dataAwsVpcPublicPrivateDeployModuleMainTf = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xac\x51\xcd\x6e\xf3\x20\x10\xbc\xfb\x29\x10\xfa\xae\xf6\xe7\xb4\x4a\x6f\x3d\xf5\xde\x4b\x8f\x55\x85\x08\x26\x11\x8a\xcd\xa2\x65\x49\x1b\x45\x7e\xf7\x82\x21\x3f\x56\xd3\x56\x91\x6a\x9f\x98\x9d\xd9\x19\x06\xd4\x1e\x02\x2a\xcd\xb8\x7c\xf7\xc2\x58\x4f\xd2\x2a\xcd\x19\x57\x60\x7d\xe8\x39\x3b\x54\x2c\x7e\x72\x30\xec\x91\xf1\x7f\x87\x9d\xc4\x26\x1e\x46\x3e\xc1\x47\xbe\xa0\xbd\xd3\x89\x40\x77\x8d\x1f\x64\xdf\xe7\xf1\x56\xef\x85\x95\x83\x3e\x4b\x23\x52\x27\xa4\xe8\x7d\x58\x59\x4d\xc2\x74\x67\x46\x86\x6a\xd3\x15\xca\xce\x29\xe1\xb5\x0a\x68\x68\x2f\x36\x08\xc1\x45\xba\x8f\xfc\xd7\x28\x48\x99\xe7\xc3\x26\xe7\x6e\x92\xfe\x6d\x5a\xe0\xd0\xec\x24\x69\x61\xdc\xd9\xa4\x60\xb5\x71\xd1\x65\x62\x91\xdc\xf8\x72\xd7\xf4\x3d\x97\xd4\x79\x1b\xcb\x2a\x63\x3b\xfd\x51\x62\x8d\xd5\x58\x55\xf3\xf2\xe6\x41\xbe\x54\x68\x7f\x5b\xd9\x69\xaf\xd0\x38\x32\x60\x13\xef\xa5\xac\x63\xd3\x3a\xb6\x06\x64\x4f\xdf\x49\x53\x49\x97\x25\xc6\x73\x6e\xb0\xbc\xd2\x26\x26\xbd\xbc\xde\x1a\x61\x10\x0e\x90\xa2\x64\x71\x42\x09\x8e\xd8\xc3\x72\x79\xbf\x3c\xe1\x0e\x81\x40\x41\x9f\xf6\x87\xce\xf1\xd3\x40\x99\x0e\xc5\xaa\x07\xb5\xcd\x0f\xd2\x36\xd3\xff\xbf\x2d\xd5\x8f\x7f\xef\x4f\xea\x76\x7f\xfd\x93\x7d\x7b\xc5\xbe\xbd\x6a\x5d\x2f\x6e\x71\x1e\xab\xcf\x00\x00\x00\xff\xff\x0e\x96\x87\x72\x5b\x03\x00\x00"

func dataAwsVpcPublicPrivateDeployModuleMainTfBytes() ([]byte, error) {
	return bindataRead(
		_dataAwsVpcPublicPrivateDeployModuleMainTf,
		"data/aws-vpc-public-private/deploy/module/main.tf",
	)
}

func dataAwsVpcPublicPrivateDeployModuleMainTf() (*asset, error) {
	bytes, err := dataAwsVpcPublicPrivateDeployModuleMainTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/aws-vpc-public-private/deploy/module/main.tf", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _dataAwsVpcPublicPrivateDeployModuleOutputsTf = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x0c\xc0\x41\x0a\x05\x21\x08\x00\xd0\x7d\xa7\x10\xf9\xeb\x6e\xf0\xcf\x12\x52\x2e\x82\x30\x49\x6d\x16\xd1\xdd\x67\xde\x0c\xd7\x70\x40\x6a\x6d\xb1\x19\xc2\x49\xf0\xd9\x34\x82\xe1\x0f\xf8\x3b\xf4\x58\xe9\x62\x4e\x52\x39\xd7\x29\x16\x23\xeb\xea\x9b\x9c\x4b\xd7\x8b\xe9\xa6\x37\x00\x00\xff\xff\x7c\x4c\xbb\x14\x45\x00\x00\x00"

func dataAwsVpcPublicPrivateDeployModuleOutputsTfBytes() ([]byte, error) {
	return bindataRead(
		_dataAwsVpcPublicPrivateDeployModuleOutputsTf,
		"data/aws-vpc-public-private/deploy/module/outputs.tf",
	)
}

func dataAwsVpcPublicPrivateDeployModuleOutputsTf() (*asset, error) {
	bytes, err := dataAwsVpcPublicPrivateDeployModuleOutputsTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/aws-vpc-public-private/deploy/module/outputs.tf", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _dataAwsVpcPublicPrivateDeployModuleVariablesTf = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x74\xce\xc1\xca\x83\x30\x0c\x07\xf0\x7b\x9f\x22\xf4\xee\x23\x7c\x87\x0f\x77\x98\x87\x81\x20\xec\x1e\x35\xdb\xc2\x34\x2d\x4d\x95\x8d\xb1\x77\x9f\x95\xc1\x40\x6c\x4f\xa5\xff\xfe\x92\xff\x8c\x81\xb1\x1d\x08\x2c\x8e\x6c\xe1\x65\x60\x39\x3d\x69\x17\xd8\x47\x76\x02\x7f\x60\xff\x4f\x15\x44\x07\x93\x12\x5c\x5c\x80\xd2\x89\x4e\x83\x35\x6f\x63\x7e\x9a\xa5\xa7\x47\xc6\x57\x29\x5b\x69\xbc\x11\x08\x8e\xb4\xc1\x77\x7a\x16\xeb\xf3\xbe\x6f\x9a\x23\x2c\x5f\xf6\xa4\x0f\x3c\x63\xa4\x82\x7d\x6e\x77\x9d\xaa\xa3\x2a\x5f\x25\xdd\x52\x03\x16\x8d\x28\xdd\x76\x96\x4e\xad\x50\x2c\xb8\xcf\xd5\x58\x73\xa8\x0e\x1b\x37\xfb\x2e\x8f\xce\x75\xf9\x15\x9f\x00\x00\x00\xff\xff\x28\x6f\x5b\x11\x6a\x01\x00\x00"

func dataAwsVpcPublicPrivateDeployModuleVariablesTfBytes() ([]byte, error) {
	return bindataRead(
		_dataAwsVpcPublicPrivateDeployModuleVariablesTf,
		"data/aws-vpc-public-private/deploy/module/variables.tf",
	)
}

func dataAwsVpcPublicPrivateDeployModuleVariablesTf() (*asset, error) {
	bytes, err := dataAwsVpcPublicPrivateDeployModuleVariablesTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/aws-vpc-public-private/deploy/module/variables.tf", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _dataAwsVpcPublicPrivateDeployVariablesTf = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xb4\x8f\x31\xcb\xc2\x30\x10\x86\xf7\xfc\x8a\x23\x99\x33\xb4\xfb\x37\x7c\x28\xa8\x5b\xa1\xa0\xa3\x5c\xdb\xb3\x06\x6b\x2c\xb9\xb4\x22\xe2\x7f\x37\xb5\x1d\x44\xac\x08\xc5\x1b\xf3\xde\xfb\xe4\x1e\xa5\x27\x8d\x50\xf0\xbf\x49\x81\xc9\x7b\x63\x4b\x16\x53\x71\x2d\x3a\x83\x59\x45\x20\xf1\xcc\x5b\x47\xa5\x39\x59\x09\x57\x01\x61\x0a\xe2\xdc\x99\xda\x87\x27\xf8\x03\xd9\xfd\x3b\x2c\x0c\xf1\x0e\x9b\xca\x77\x51\xc3\x9a\x90\xbd\x8e\xa4\xb8\x89\xc9\x37\x29\x58\x90\x25\x87\xd5\x2f\x34\x99\xf7\xfa\x40\x97\x11\xc7\x34\x5d\x42\x48\xc1\xe2\x91\x1e\x2e\x4f\xc5\x26\xb3\xe4\x75\xed\x4c\x8b\x9e\x82\xea\x7b\x42\xd2\xe7\xd0\xaf\x83\x8a\x3e\x63\xe2\x2f\x31\xf1\x0b\xa6\xad\x73\x6d\x8a\x91\xf2\x3a\x99\xc1\x6a\xde\x35\xee\x01\x00\x00\xff\xff\x54\xa5\xca\xa8\x6e\x02\x00\x00"

func dataAwsVpcPublicPrivateDeployVariablesTfBytes() ([]byte, error) {
	return bindataRead(
		_dataAwsVpcPublicPrivateDeployVariablesTf,
		"data/aws-vpc-public-private/deploy/variables.tf",
	)
}

func dataAwsVpcPublicPrivateDeployVariablesTf() (*asset, error) {
	bytes, err := dataAwsVpcPublicPrivateDeployVariablesTfBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "data/aws-vpc-public-private/deploy/variables.tf", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if (err != nil) {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"data/aws-vpc-public-private/deploy/main.tf": dataAwsVpcPublicPrivateDeployMainTf,
	"data/aws-vpc-public-private/deploy/module/main.tf": dataAwsVpcPublicPrivateDeployModuleMainTf,
	"data/aws-vpc-public-private/deploy/module/outputs.tf": dataAwsVpcPublicPrivateDeployModuleOutputsTf,
	"data/aws-vpc-public-private/deploy/module/variables.tf": dataAwsVpcPublicPrivateDeployModuleVariablesTf,
	"data/aws-vpc-public-private/deploy/variables.tf": dataAwsVpcPublicPrivateDeployVariablesTf,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"data": &bintree{nil, map[string]*bintree{
		"aws-vpc-public-private": &bintree{nil, map[string]*bintree{
			"deploy": &bintree{nil, map[string]*bintree{
				"main.tf": &bintree{dataAwsVpcPublicPrivateDeployMainTf, map[string]*bintree{
				}},
				"module": &bintree{nil, map[string]*bintree{
					"main.tf": &bintree{dataAwsVpcPublicPrivateDeployModuleMainTf, map[string]*bintree{
					}},
					"outputs.tf": &bintree{dataAwsVpcPublicPrivateDeployModuleOutputsTf, map[string]*bintree{
					}},
					"variables.tf": &bintree{dataAwsVpcPublicPrivateDeployModuleVariablesTf, map[string]*bintree{
					}},
				}},
				"variables.tf": &bintree{dataAwsVpcPublicPrivateDeployVariablesTf, map[string]*bintree{
				}},
			}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
        data, err := Asset(name)
        if err != nil {
                return err
        }
        info, err := AssetInfo(name)
        if err != nil {
                return err
        }
        err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
        if err != nil {
                return err
        }
        err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
        if err != nil {
                return err
        }
        err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
        if err != nil {
                return err
        }
        return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
        children, err := AssetDir(name)
        // File
        if err != nil {
                return RestoreAsset(dir, name)
        }
        // Dir
        for _, child := range children {
                err = RestoreAssets(dir, filepath.Join(name, child))
                if err != nil {
                        return err
                }
        }
        return nil
}

func _filePath(dir, name string) string {
        cannonicalName := strings.Replace(name, "\\", "/", -1)
        return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

