# Generated by Otto, do not edit manually.

variable "openstack_auth_url" {
    description = "OpenStack authentification URL endpoint (Keystone v2 only)"
}

variable "openstack_tenant_name" {
    description = "OpenStack tenant name"
}

variable "openstack_username" {
    description = "OpenStack user name"
}

variable "openstack_password" {
    description = "OpenStack user password"
}

variable "openstack_region_name" {
    description = "OpenStack region name"
}

variable "openstack_image_id" {
    description = "Image ID for the OpenStack virtual machine"
}

variable "openstack_flavor_id" {
    description = "Flavor ID for the OpenStack virtual machine"
}

variable "openstack_floating_ip_pool" {
    description = "OpenStack floating IP pool used to get public IPs"
}

variable "openstack_ssh_username" {
    description = "Username used to SSH into the OpenStack instances"
}

variable "openstack_external_gateway" {
    description = "External gateway that will be used to connect routers"
}

variable "ssh_public_key_path" {
    description = "Contents of an SSH public key to grant access to created instances"
}
