# Generated by Otto, do not edit manually.

resource "openstack_networking_network_v2" "net" {
    name = "otto"
}

resource "openstack_networking_subnet_v2" "subnet" {
    network_id = "${openstack_networking_network_v2.net.id}"
    cidr = "10.0.0.0/16"
    ip_version = 4
    dns_nameservers = ["8.8.8.8", "8.8.4.4"]
}

resource "openstack_networking_router_v2" "router" {
  name = "otto"
  external_gateway = "${var.openstack_external_gateway}"
}

resource "openstack_networking_router_interface_v2" "net_interface" {
    router_id = "${openstack_networking_router_v2.router.id}"
    subnet_id = "${openstack_networking_subnet_v2.subnet.id}"
}

resource "openstack_compute_secgroup_v2" "secgroup" {
  name = "otto"
  description = "otto security group"
  rule {
      from_port = 1
      to_port = 65535
      ip_protocol = "tcp"
      cidr = "0.0.0.0/0"
  }
  rule {
      from_port = 1
      to_port = 65535
      ip_protocol = "udp"
      cidr = "0.0.0.0/0"
  }
  rule {
      from_port = -1
      to_port = -1
      ip_protocol = "icmp"
      cidr = "0.0.0.0/0"
  }
}
