# Generated by Otto, do not edit manually.
#
# Otto uses outputs as the method for transferring data from Terraform
# back into Otto that will be used for deploys, future infrastructure
# change, etc.
#
# Because of the importance of these values for Otto to function, care
# should be taken if these are modified.

output "region" {
    value = "${var.openstack_region_name}"
}

output "network_id" {
    value = "${openstack_networking_network_v2.net.id}"
}

output "security_group" {
    value = "${openstack_compute_secgroup_v2.secgroup.name}"
}
