# Generated by Otto, do not edit manually

variable "do_token" {}
variable "do_ssh_public_key_path" {}
variable "image" {}
variable "size" { default = "512mb" }
variable "region" { default = "sfo1" }

provider "digitalocean" {
  token = "${var.do_token}"
}

resource "digitalocean_ssh_key" "default" {
  name = "do-otto-key"
  public_key = "${file(var.do_ssh_public_key_path)}"
}

resource "digitalocean_droplet" "app" {
  image              = "${var.image}"
  region             = "${var.region}"
  name               = "otto-${count.index}"
  size               = "${var.size}"
  depends_on         = ["digitalocean_ssh_key.default"]
  private_networking = true
  user_data          = "{role: {{ name }} }"
  ssh_keys = [
    "${digitalocean_ssh_key.default.id}"
  ]
}

output "url" {
  value = "http://${digitalocean_droplet.app.ipv4_address}/"
}
