// Code generated by "stringer -type=DeployState deploy_state.go"; DO NOT EDIT

package directory

import "fmt"

const _DeployState_name = "DeployStateInvalidDeployStateNewDeployStateFailDeployStateSuccess"

var _DeployState_index = [...]uint8{0, 18, 32, 47, 65}

func (i DeployState) String() string {
	if i >= DeployState(len(_DeployState_index)-1) {
		return fmt.Sprintf("DeployState(%d)", i)
	}
	return _DeployState_name[_DeployState_index[i]:_DeployState_index[i+1]]
}
