// generated by stringer -type=InfraState infra_state.go; DO NOT EDIT

package directory

import "fmt"

const _InfraState_name = "InfraStateInvalidInfraStatePartialInfraStateReady"

var _InfraState_index = [...]uint8{0, 17, 34, 49}

func (i InfraState) String() string {
	if i >= InfraState(len(_InfraState_index)-1) {
		return fmt.Sprintf("InfraState(%d)", i)
	}
	return _InfraState_name[_InfraState_index[i]:_InfraState_index[i+1]]
}
