# Generated by Otto, do not edit!
#
# This is a Vagrantfile that represents a single layer of a multi-layered
# dev environment. Do not modify, boot, or destroy this environment since
# it can corrupt other environments very easily.

Vagrant.configure("2") do |config|
  {% block vagrant_box %}
  config.vm.box = "hashicorp/precise64"
  config.vm.provider :parallels do |p, o|
    o.vm.box = "parallels/ubuntu-12.04"
  end
  {% endblock %}

  # Disable the default synced folder
  config.vm.synced_folder ".", "/vagrant", disabled: true

  {% block vagrant_config %}{% endblock %}
end

{% block footer %}{% endblock %}
