# Generated by Otto, do not edit manually.

# Main VPC that will contain everything.
resource "aws_vpc" "main" {
    cidr_block = "10.0.0.0/16"

    tags {
        Name = "otto"
    }
}

# The public subnet is where resources connected to the internet will go
resource "aws_subnet" "public" {
    vpc_id = "${aws_vpc.main.id}"
    cidr_block = "10.0.1.0/24"

    tags {
        Name = "public"
    }
}

# The private subnet is where resources that are internal only will go
resource "aws_subnet" "private" {
    vpc_id = "${aws_vpc.main.id}"
    cidr_block = "10.0.2.0/24"

    tags {
        Name = "private"
    }
}
