# Generated by Otto, do not edit manually.
#
# Otto uses outputs as the method for transferring data from Terraform
# back into Otto that will be used for deploys, future infrastructure
# change, etc.
#
# Because of the importance of these values for Otto to function, care
# should be taken if these are modified.

output "vpc_id" {
    value = "${aws_vpc.main.id}"
}

output "subnet-public" {
    value = "${aws_subnet.public.id}"
}

output "subnet-private" {
    value = "${aws_subnet.private.id}"
}
