// Code generated by go-bindata.
// sources:
// test-data/copy-dir-basic/a.txt
// test-data/copy-dir-basic/b.txt
// test-data/copy-dir-basic/dir/c.txt
// test-data/copy-dir-basic/t.tpl
// test-data/copy-dir-basic-expected/a.txt
// test-data/copy-dir-basic-expected/b.txt
// test-data/copy-dir-basic-expected/dir/c.txt
// test-data/copy-dir-basic-expected/t
// test-data/copy-dir-extends/a.tpl
// test-data/copy-dir-extends/base
// test-data/copy-dir-extends/base.tpl
// test-data/copy-dir-extends-expected/a
// test-data/copy-dir-extends-expected/base
// test-data/copy-dir-extends-var/a.tpl
// test-data/copy-dir-extends-var/base.tpl
// test-data/copy-dir-extends-var-expected/a
// test-data/copy-dir-extends-var-expected/base
// test-data/copy-dir-include/a.tpl
// test-data/copy-dir-include/b
// test-data/copy-dir-include-expected/a
// test-data/copy-dir-include-expected/b
// test-data/copy-dir-shared/a.tpl
// test-data/copy-dir-shared-expected/a
// DO NOT EDIT!

package bindata

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"strings"
	"os"
	"time"
	"io/ioutil"
	"path/filepath"
)

func bindataRead(data, name string) ([]byte, error) {
	gz, err := gzip.NewReader(strings.NewReader(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name string
	size int64
	mode os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _testDataCopyDirBasicATxt = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x72\xe4\x02\x04\x00\x00\xff\xff\xa5\x85\x6e\x48\x02\x00\x00\x00"

func testDataCopyDirBasicATxtBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirBasicATxt,
		"test-data/copy-dir-basic/a.txt",
	)
}

func testDataCopyDirBasicATxt() (*asset, error) {
	bytes, err := testDataCopyDirBasicATxtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-basic/a.txt", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirBasicBTxt = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x72\xe2\x02\x04\x00\x00\xff\xff\x66\xd6\x43\x63\x02\x00\x00\x00"

func testDataCopyDirBasicBTxtBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirBasicBTxt,
		"test-data/copy-dir-basic/b.txt",
	)
}

func testDataCopyDirBasicBTxt() (*asset, error) {
	bytes, err := testDataCopyDirBasicBTxtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-basic/b.txt", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirBasicDirCTxt = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x72\xe6\x02\x04\x00\x00\xff\xff\x27\xe7\x58\x7a\x02\x00\x00\x00"

func testDataCopyDirBasicDirCTxtBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirBasicDirCTxt,
		"test-data/copy-dir-basic/dir/c.txt",
	)
}

func testDataCopyDirBasicDirCTxt() (*asset, error) {
	bytes, err := testDataCopyDirBasicDirCTxtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-basic/dir/c.txt", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirBasicTTpl = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x72\x2e\x2d\x2a\x4a\xcd\x2b\x51\x88\x4c\x4d\x2c\xb2\x52\xa8\xae\x56\x28\x4b\xcc\x29\x4d\x55\xa8\xad\xe5\x02\x04\x00\x00\xff\xff\xc8\x33\xc7\x9f\x1a\x00\x00\x00"

func testDataCopyDirBasicTTplBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirBasicTTpl,
		"test-data/copy-dir-basic/t.tpl",
	)
}

func testDataCopyDirBasicTTpl() (*asset, error) {
	bytes, err := testDataCopyDirBasicTTplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-basic/t.tpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirBasicExpectedATxt = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x72\xe4\x02\x04\x00\x00\xff\xff\xa5\x85\x6e\x48\x02\x00\x00\x00"

func testDataCopyDirBasicExpectedATxtBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirBasicExpectedATxt,
		"test-data/copy-dir-basic-expected/a.txt",
	)
}

func testDataCopyDirBasicExpectedATxt() (*asset, error) {
	bytes, err := testDataCopyDirBasicExpectedATxtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-basic-expected/a.txt", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirBasicExpectedBTxt = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x72\xe2\x02\x04\x00\x00\xff\xff\x66\xd6\x43\x63\x02\x00\x00\x00"

func testDataCopyDirBasicExpectedBTxtBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirBasicExpectedBTxt,
		"test-data/copy-dir-basic-expected/b.txt",
	)
}

func testDataCopyDirBasicExpectedBTxt() (*asset, error) {
	bytes, err := testDataCopyDirBasicExpectedBTxtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-basic-expected/b.txt", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirBasicExpectedDirCTxt = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x72\xe6\x02\x04\x00\x00\xff\xff\x27\xe7\x58\x7a\x02\x00\x00\x00"

func testDataCopyDirBasicExpectedDirCTxtBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirBasicExpectedDirCTxt,
		"test-data/copy-dir-basic-expected/dir/c.txt",
	)
}

func testDataCopyDirBasicExpectedDirCTxt() (*asset, error) {
	bytes, err := testDataCopyDirBasicExpectedDirCTxtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-basic-expected/dir/c.txt", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirBasicExpectedT = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x72\x2e\x2d\x2a\x4a\xcd\x2b\x51\x88\x4c\x4d\x2c\xb2\x52\x48\xcb\xcf\xe7\x02\x04\x00\x00\xff\xff\x34\x06\xb8\x03\x12\x00\x00\x00"

func testDataCopyDirBasicExpectedTBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirBasicExpectedT,
		"test-data/copy-dir-basic-expected/t",
	)
}

func testDataCopyDirBasicExpectedT() (*asset, error) {
	bytes, err := testDataCopyDirBasicExpectedTBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-basic-expected/t", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirExtendsATpl = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xaa\x56\x55\x48\xad\x28\x49\xcd\x4b\x29\x56\x50\x4a\x4a\x2c\x4e\xd5\x2b\x29\xc8\x51\x52\x50\xad\xe5\x02\x04\x00\x00\xff\xff\x23\xb9\xd9\xe8\x19\x00\x00\x00"

func testDataCopyDirExtendsATplBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirExtendsATpl,
		"test-data/copy-dir-extends/a.tpl",
	)
}

func testDataCopyDirExtendsATpl() (*asset, error) {
	bytes, err := testDataCopyDirExtendsATplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-extends/a.tpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirExtendsBase = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xf2\x70\xf5\xf1\xf1\x57\xe4\x02\x04\x00\x00\xff\xff\x72\x1b\x50\xee\x07\x00\x00\x00"

func testDataCopyDirExtendsBaseBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirExtendsBase,
		"test-data/copy-dir-extends/base",
	)
}

func testDataCopyDirExtendsBase() (*asset, error) {
	bytes, err := testDataCopyDirExtendsBaseBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-extends/base", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirExtendsBaseTpl = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xf2\x70\xf5\xf1\xf1\x57\xe4\x02\x04\x00\x00\xff\xff\x72\x1b\x50\xee\x07\x00\x00\x00"

func testDataCopyDirExtendsBaseTplBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirExtendsBaseTpl,
		"test-data/copy-dir-extends/base.tpl",
	)
}

func testDataCopyDirExtendsBaseTpl() (*asset, error) {
	bytes, err := testDataCopyDirExtendsBaseTplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-extends/base.tpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirExtendsExpectedA = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xf2\x70\xf5\xf1\xf1\x57\xe4\x02\x04\x00\x00\xff\xff\x72\x1b\x50\xee\x07\x00\x00\x00"

func testDataCopyDirExtendsExpectedABytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirExtendsExpectedA,
		"test-data/copy-dir-extends-expected/a",
	)
}

func testDataCopyDirExtendsExpectedA() (*asset, error) {
	bytes, err := testDataCopyDirExtendsExpectedABytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-extends-expected/a", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirExtendsExpectedBase = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xf2\x70\xf5\xf1\xf1\x57\xe4\x02\x04\x00\x00\xff\xff\x72\x1b\x50\xee\x07\x00\x00\x00"

func testDataCopyDirExtendsExpectedBaseBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirExtendsExpectedBase,
		"test-data/copy-dir-extends-expected/base",
	)
}

func testDataCopyDirExtendsExpectedBase() (*asset, error) {
	bytes, err := testDataCopyDirExtendsExpectedBaseBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-extends-expected/base", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirExtendsVarATpl = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xaa\x56\x55\x48\xad\x28\x49\xcd\x4b\x29\x56\x50\x4a\x4a\x2c\x4e\xd5\x2b\x29\xc8\x51\x52\x50\xad\xe5\xe2\x02\xca\x24\xe5\xe4\x27\x67\x2b\xa4\xe5\xe7\x03\x05\xc2\x3d\x1c\x43\x40\x8a\xf3\x52\x20\xa2\x40\x25\x80\x00\x00\x00\xff\xff\x9d\x4c\xa7\xf3\x3c\x00\x00\x00"

func testDataCopyDirExtendsVarATplBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirExtendsVarATpl,
		"test-data/copy-dir-extends-var/a.tpl",
	)
}

func testDataCopyDirExtendsVarATpl() (*asset, error) {
	bytes, err := testDataCopyDirExtendsVarATplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-extends-var/a.tpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirExtendsVarBaseTpl = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xf2\x48\xcd\xc9\xc9\x57\xa8\xae\x56\x28\x4b\xcc\x29\x4d\x55\xa8\xad\xe5\xe2\xaa\x56\x55\x48\xca\xc9\x4f\xce\x56\x48\xcb\xcf\x57\x50\xad\x05\x72\x53\xf3\x52\x20\x22\xaa\x40\xe9\xa4\xc4\x22\x2e\x40\x00\x00\x00\xff\xff\xf8\xea\x6e\xfb\x36\x00\x00\x00"

func testDataCopyDirExtendsVarBaseTplBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirExtendsVarBaseTpl,
		"test-data/copy-dir-extends-var/base.tpl",
	)
}

func testDataCopyDirExtendsVarBaseTpl() (*asset, error) {
	bytes, err := testDataCopyDirExtendsVarBaseTplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-extends-var/base.tpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirExtendsVarExpectedA = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xf2\x48\xcd\xc9\xc9\x57\x48\xcb\xcf\xe7\xe2\x0a\xf7\x70\x0c\xe1\xe2\x4a\x4a\x2c\xe2\x02\x04\x00\x00\xff\xff\x22\xf4\xc2\x1f\x15\x00\x00\x00"

func testDataCopyDirExtendsVarExpectedABytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirExtendsVarExpectedA,
		"test-data/copy-dir-extends-var-expected/a",
	)
}

func testDataCopyDirExtendsVarExpectedA() (*asset, error) {
	bytes, err := testDataCopyDirExtendsVarExpectedABytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-extends-var-expected/a", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirExtendsVarExpectedBase = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xf2\x48\xcd\xc9\xc9\x57\x48\xcb\xcf\xe7\x02\x82\xa4\xc4\x22\x2e\x40\x00\x00\x00\xff\xff\x91\xf4\xda\x41\x11\x00\x00\x00"

func testDataCopyDirExtendsVarExpectedBaseBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirExtendsVarExpectedBase,
		"test-data/copy-dir-extends-var-expected/base",
	)
}

func testDataCopyDirExtendsVarExpectedBase() (*asset, error) {
	bytes, err := testDataCopyDirExtendsVarExpectedBaseBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-extends-var-expected/base", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirIncludeATpl = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xf2\x48\xcd\xc9\xc9\xe7\xe2\xaa\x56\x55\xc8\xcc\x4b\xce\x29\x4d\x49\x55\x50\x4a\x52\x52\x50\xad\xe5\x72\xcb\xcf\xe7\x02\x04\x00\x00\xff\xff\x97\xd1\xc7\xfd\x1d\x00\x00\x00"

func testDataCopyDirIncludeATplBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirIncludeATpl,
		"test-data/copy-dir-include/a.tpl",
	)
}

func testDataCopyDirIncludeATpl() (*asset, error) {
	bytes, err := testDataCopyDirIncludeATplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-include/a.tpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirIncludeB = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x0a\xcf\x2f\xca\x49\xe1\x02\x04\x00\x00\xff\xff\x9e\x64\x94\xda\x06\x00\x00\x00"

func testDataCopyDirIncludeBBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirIncludeB,
		"test-data/copy-dir-include/b",
	)
}

func testDataCopyDirIncludeB() (*asset, error) {
	bytes, err := testDataCopyDirIncludeBBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-include/b", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirIncludeExpectedA = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xf2\x48\xcd\xc9\xc9\xe7\xe2\x0a\xcf\x2f\xca\x49\xe1\xe2\x72\xcb\xcf\xe7\x02\x04\x00\x00\xff\xff\x35\x22\xeb\x9d\x12\x00\x00\x00"

func testDataCopyDirIncludeExpectedABytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirIncludeExpectedA,
		"test-data/copy-dir-include-expected/a",
	)
}

func testDataCopyDirIncludeExpectedA() (*asset, error) {
	bytes, err := testDataCopyDirIncludeExpectedABytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-include-expected/a", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirIncludeExpectedB = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x0a\xcf\x2f\xca\x49\xe1\x02\x04\x00\x00\xff\xff\x9e\x64\x94\xda\x06\x00\x00\x00"

func testDataCopyDirIncludeExpectedBBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirIncludeExpectedB,
		"test-data/copy-dir-include-expected/b",
	)
}

func testDataCopyDirIncludeExpectedB() (*asset, error) {
	bytes, err := testDataCopyDirIncludeExpectedBBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-include-expected/b", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirSharedATpl = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xaa\x56\x55\x48\xad\x28\x49\xcd\x4b\x29\x56\x50\x4a\xcb\xcf\xb7\x4a\x49\x2c\x49\xd4\x4f\x4a\x2c\x4e\xd5\x2b\x29\xc8\x51\x52\x50\xad\xe5\x02\x04\x00\x00\xff\xff\x50\xc2\x51\x17\x22\x00\x00\x00"

func testDataCopyDirSharedATplBytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirSharedATpl,
		"test-data/copy-dir-shared/a.tpl",
	)
}

func testDataCopyDirSharedATpl() (*asset, error) {
	bytes, err := testDataCopyDirSharedATplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-shared/a.tpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _testDataCopyDirSharedExpectedA = "\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xf2\x48\xcd\xc9\xc9\x57\x48\x2b\xca\xcf\x55\x28\x49\x2d\x2e\xe1\x02\x04\x00\x00\xff\xff\x3c\x1f\x65\x35\x10\x00\x00\x00"

func testDataCopyDirSharedExpectedABytes() ([]byte, error) {
	return bindataRead(
		_testDataCopyDirSharedExpectedA,
		"test-data/copy-dir-shared-expected/a",
	)
}

func testDataCopyDirSharedExpectedA() (*asset, error) {
	bytes, err := testDataCopyDirSharedExpectedABytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test-data/copy-dir-shared-expected/a", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if (err != nil) {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"test-data/copy-dir-basic/a.txt": testDataCopyDirBasicATxt,
	"test-data/copy-dir-basic/b.txt": testDataCopyDirBasicBTxt,
	"test-data/copy-dir-basic/dir/c.txt": testDataCopyDirBasicDirCTxt,
	"test-data/copy-dir-basic/t.tpl": testDataCopyDirBasicTTpl,
	"test-data/copy-dir-basic-expected/a.txt": testDataCopyDirBasicExpectedATxt,
	"test-data/copy-dir-basic-expected/b.txt": testDataCopyDirBasicExpectedBTxt,
	"test-data/copy-dir-basic-expected/dir/c.txt": testDataCopyDirBasicExpectedDirCTxt,
	"test-data/copy-dir-basic-expected/t": testDataCopyDirBasicExpectedT,
	"test-data/copy-dir-extends/a.tpl": testDataCopyDirExtendsATpl,
	"test-data/copy-dir-extends/base": testDataCopyDirExtendsBase,
	"test-data/copy-dir-extends/base.tpl": testDataCopyDirExtendsBaseTpl,
	"test-data/copy-dir-extends-expected/a": testDataCopyDirExtendsExpectedA,
	"test-data/copy-dir-extends-expected/base": testDataCopyDirExtendsExpectedBase,
	"test-data/copy-dir-extends-var/a.tpl": testDataCopyDirExtendsVarATpl,
	"test-data/copy-dir-extends-var/base.tpl": testDataCopyDirExtendsVarBaseTpl,
	"test-data/copy-dir-extends-var-expected/a": testDataCopyDirExtendsVarExpectedA,
	"test-data/copy-dir-extends-var-expected/base": testDataCopyDirExtendsVarExpectedBase,
	"test-data/copy-dir-include/a.tpl": testDataCopyDirIncludeATpl,
	"test-data/copy-dir-include/b": testDataCopyDirIncludeB,
	"test-data/copy-dir-include-expected/a": testDataCopyDirIncludeExpectedA,
	"test-data/copy-dir-include-expected/b": testDataCopyDirIncludeExpectedB,
	"test-data/copy-dir-shared/a.tpl": testDataCopyDirSharedATpl,
	"test-data/copy-dir-shared-expected/a": testDataCopyDirSharedExpectedA,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"test-data": &bintree{nil, map[string]*bintree{
		"copy-dir-basic": &bintree{nil, map[string]*bintree{
			"a.txt": &bintree{testDataCopyDirBasicATxt, map[string]*bintree{
			}},
			"b.txt": &bintree{testDataCopyDirBasicBTxt, map[string]*bintree{
			}},
			"dir": &bintree{nil, map[string]*bintree{
				"c.txt": &bintree{testDataCopyDirBasicDirCTxt, map[string]*bintree{
				}},
			}},
			"t.tpl": &bintree{testDataCopyDirBasicTTpl, map[string]*bintree{
			}},
		}},
		"copy-dir-basic-expected": &bintree{nil, map[string]*bintree{
			"a.txt": &bintree{testDataCopyDirBasicExpectedATxt, map[string]*bintree{
			}},
			"b.txt": &bintree{testDataCopyDirBasicExpectedBTxt, map[string]*bintree{
			}},
			"dir": &bintree{nil, map[string]*bintree{
				"c.txt": &bintree{testDataCopyDirBasicExpectedDirCTxt, map[string]*bintree{
				}},
			}},
			"t": &bintree{testDataCopyDirBasicExpectedT, map[string]*bintree{
			}},
		}},
		"copy-dir-extends": &bintree{nil, map[string]*bintree{
			"a.tpl": &bintree{testDataCopyDirExtendsATpl, map[string]*bintree{
			}},
			"base": &bintree{testDataCopyDirExtendsBase, map[string]*bintree{
			}},
			"base.tpl": &bintree{testDataCopyDirExtendsBaseTpl, map[string]*bintree{
			}},
		}},
		"copy-dir-extends-expected": &bintree{nil, map[string]*bintree{
			"a": &bintree{testDataCopyDirExtendsExpectedA, map[string]*bintree{
			}},
			"base": &bintree{testDataCopyDirExtendsExpectedBase, map[string]*bintree{
			}},
		}},
		"copy-dir-extends-var": &bintree{nil, map[string]*bintree{
			"a.tpl": &bintree{testDataCopyDirExtendsVarATpl, map[string]*bintree{
			}},
			"base.tpl": &bintree{testDataCopyDirExtendsVarBaseTpl, map[string]*bintree{
			}},
		}},
		"copy-dir-extends-var-expected": &bintree{nil, map[string]*bintree{
			"a": &bintree{testDataCopyDirExtendsVarExpectedA, map[string]*bintree{
			}},
			"base": &bintree{testDataCopyDirExtendsVarExpectedBase, map[string]*bintree{
			}},
		}},
		"copy-dir-include": &bintree{nil, map[string]*bintree{
			"a.tpl": &bintree{testDataCopyDirIncludeATpl, map[string]*bintree{
			}},
			"b": &bintree{testDataCopyDirIncludeB, map[string]*bintree{
			}},
		}},
		"copy-dir-include-expected": &bintree{nil, map[string]*bintree{
			"a": &bintree{testDataCopyDirIncludeExpectedA, map[string]*bintree{
			}},
			"b": &bintree{testDataCopyDirIncludeExpectedB, map[string]*bintree{
			}},
		}},
		"copy-dir-shared": &bintree{nil, map[string]*bintree{
			"a.tpl": &bintree{testDataCopyDirSharedATpl, map[string]*bintree{
			}},
		}},
		"copy-dir-shared-expected": &bintree{nil, map[string]*bintree{
			"a": &bintree{testDataCopyDirSharedExpectedA, map[string]*bintree{
			}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
        data, err := Asset(name)
        if err != nil {
                return err
        }
        info, err := AssetInfo(name)
        if err != nil {
                return err
        }
        err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
        if err != nil {
                return err
        }
        err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
        if err != nil {
                return err
        }
        err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
        if err != nil {
                return err
        }
        return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
        children, err := AssetDir(name)
        // File
        if err != nil {
                return RestoreAsset(dir, name)
        }
        // Dir
        for _, child := range children {
                err = RestoreAssets(dir, filepath.Join(name, child))
                if err != nil {
                        return err
                }
        }
        return nil
}

func _filePath(dir, name string) string {
        cannonicalName := strings.Replace(name, "\\", "/", -1)
        return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

