# Generated by Otto, do not edit manually

variable "openstack_auth_url" {}
variable "openstack_username" {}
variable "openstack_tenant_name" {}
variable "openstack_password" {}
variable "openstack_region_name" {}
variable "openstack_flavor_id" {}
variable "openstack_floating_ip_pool" {}

variable "network_id" {}
variable "security_group" {}
variable "ssh_public_key_path" {}

variable "image" {}

provider "openstack" {
  auth_url    = "${var.openstack_auth_url}"
  user_name   = "${var.openstack_username}"
  tenant_name = "${var.openstack_tenant_name}"
  password    = "${var.openstack_password}"
}

resource "openstack_networking_floatingip_v2" "fip" {
    pool = "${var.openstack_floating_ip_pool}"
}

resource "openstack_compute_keypair_v2" "keypair" {
    name = "{{ name }}"
    public_key = "${file("${var.ssh_public_key_path}")}"
}

resource "openstack_compute_instance_v2" "instance" {
    name = "{{ name }}"
    image_id = "${var.image}"
    flavor_id = "${var.openstack_flavor_id}"
    network = {
        uuid = "${var.network_id}"
    }
    security_groups = ["${var.security_group}"]
    floating_ip = "${openstack_networking_floatingip_v2.fip.address}"
    key_pair = "${openstack_compute_keypair_v2.keypair.name}"
    region = "${var.openstack_region_name}"
}

output "url" {
  value = "http://${openstack_networking_floatingip_v2.fip.address}"
}
